
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/external)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/external/protobuf)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/external/lua5.3)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/common)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/libmsg)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/luamsg)


LINK_DIRECTORIES(${CMAKE_SOURCE_DIR}/external/libs)
LINK_DIRECTORIES(${CMAKE_BINARY_DIR})

SET(EXECUTABLE_OUTPUT_PATH "D:/2017code/ws/output")
SET(LIBRARY_OUT_PATH "D:/2017code/ws/output")


